### PR TITLE
Fix methods for attributes with dimensions

### LINKED ISSUE #126: `create_element!` does not support attributes with dimension
We define if an attribute has dimension > 0 in the PMD file

```
DEFINE_MODEL MODL:SDDP_ElectrificationDemandSegment
        DIMENSION	block
	VETOR DATE 	Data
	VETOR REAL 	Demanda	DIM(block) INDEX Data  🔴 
	VETOR DATE 	DataCusto
	VETOR REAL 	Custo	DIM(block) INDEX DataCusto   🔴 

	//--------------------------------------
	//--- Demanda Horaria                ---
	//--------------------------------------
	VETOR DATE 	DataHourDemand
	VETOR REAL 	HourDemand INDEX DataHourDemand
	VETOR DATE 	DataHourDemandPrice
	VETOR REAL 	HourDemandPrice INDEX DataHourDemandPrice
END_MODEL
```

And currently, when we parse a PMD file, we create a `Vector{Dict{String , Attribute}}` for `data.data_struct`. An `Attribute` has the following structure: 

```julia
Attribute(
       "Attribute name", 
       is_a_vector,  # bool
       Type,
       Dimension,    # 0<= dimension
       "Attribute that works as index to the vector"  # can be ""
)
```

So for the attributes `Demanda` and `Custo` from `PSRDemandSegment`, the dimension parameter is 1.

```julia
Dict{String, PSRClassesInterface.PMD.Attribute}(
      ... ,
      "Demanda" => PSRClassesInterface.PMD.Attribute("Demanda", true, Float64, 1, "Data"), 
      "Custo" => PSRClassesInterface.PMD.Attribute("Custo", true, Float64, 1, "DataCusto"), 
      ...
)

```

However, when we try to create an element from `PSRDemandSegment` (or any other that has attributes with dimension > 0), we cannot define the attribute value for each block/segment/stage.

```julia
julia> PSRI.create_element!(data, "PSRDemandSegment", "Demanda(1)" => [1.0,1.2,1.3])
ERROR: Invalid attributes for collection 'PSRDemandSegment':
    Demanda(1)

```

That happens because when creating an element, we check if the attribute name is a key for the `data.data_struct[collection]` dictionary, and there's no `Demanda(1)` key, only `Demanda`. 

```julia
function _validate_element(data::Data, collection::String, element::Dict{String,Any})
    data_struct = get_data_struct(data)

    collection_struct = data_struct[collection]
    collection_keys = Set{String}(keys(collection_struct))

    element_keys = Set{String}(keys(element))
    missing_keys = setdiff(collection_keys, element_keys)
    invalid_keys = setdiff(element_keys, collection_keys)

   ... 

    if !isempty(invalid_keys)
        error("""
              Invalid attributes for collection '$collection':
                  $(join(invalid_keys, "\n    "))
              """)
    end

   ...
    return nothing
end

```

### PR DESCRIPTION
**Pull request by pedroripper**
This PR closes #126

### CODE REVIEW

**Review by guilhermebodin — APPROVED** [review]

File: src/OpenStudy/study_openinterface.jl [hunk 1]
```diff
@@ -183,6 +187,7 @@ function _findfirst_date(date::Dates.Date, vec::Vector) # TODO type this vecto w
         error("empty vector of dates")
         # return 1
     end
+
```
Comment (guilhermebodin) [inline src/OpenStudy/study_openinterface.jl:190]: why?

File: src/OpenStudy/vector_map.jl [hunk 2]
```diff
@@ -51,7 +51,9 @@ function mapped_vector(
         error("Attribute $attribute was already mapped.")
     end
 
+
```
Comment (guilhermebodin) [inline src/OpenStudy/vector_map.jl:54]: why?

File: src/OpenStudy/vector_map.jl [hunk 3]
```diff
@@ -51,7 +51,9 @@ function mapped_vector(
         error("Attribute $attribute was already mapped.")
     end
 
+    
     out = T[default for _ in 1:n] #zeros(T, n)
+
```
Comment (guilhermebodin) [inline src/OpenStudy/vector_map.jl:56]: why?

File: src/PMD/PMD.jl [hunk 4]
```diff
@@ -270,7 +269,7 @@ function _parse_pmd_line!(
         for i in 1:_MAX_MERGE
             if !haskey(data_struct[state.collection], "_MERGE_$i")
                 data_struct[state.collection]["_MERGE_$i"] = Attribute(model_template.inv[model_name], false, DataType, 0, "")
-                
+
```
Comment (guilhermebodin) [inline src/PMD/PMD.jl:272]: why?

File: src/modification_api.jl [hunk 5]
```diff
@@ -408,8 +408,13 @@ function create_study(
         defaults = Dict{String,Any}()
     end
 
+    study_defaults = Dict{String,Any}()
+
+
```
Comment (guilhermebodin) [inline src/modification_api.jl:413]: why?

File: src/modification_api.jl [hunk 6]
```diff
@@ -433,25 +438,69 @@ function create_study(
...
+        elseif (
+            haskey(study_defaults[study_collection], "DurationModel") &&
+            haskey(study_defaults[study_collection]["DurationModel"], "Duracao($number_blocks)")
+        )
+            VARIABLE_DURATION
+        else
+            FIXED_DURATION
+        end
+
+
```
Comment (guilhermebodin) [inline src/modification_api.jl:484]: why?

File: src/utils.jl [hunk 7]
```diff
@@ -173,17 +173,31 @@ function _year_stage(
...
     else
-        return m[1]
+        dim = [parse(Int32, i) for i in dim[1] if i != ',']
+        return attr[1], dim
     end
 end
 
+function _get_dim_from_attribute_name(attribute::String)
+    attr, dim = _trim_multidimensional_attribute(attribute)
+
```
Comment (guilhermebodin) [inline src/utils.jl:192]: why?

File: src/utils.jl [hunk 8]
```diff
@@ -173,17 +173,31 @@ function _year_stage(
...
+    if isnothing(dim)
+        return 0
+    end
+
```
Comment (guilhermebodin) [inline src/utils.jl:196]: why?

File: src/utils.jl [hunk 9]
```diff
@@ -173,17 +173,31 @@ function _year_stage(
...
+    return length(dim)
+end
+
+
```
Comment (guilhermebodin) [inline src/utils.jl:200]: why?

**Review by guilhermebodin — CHANGES_REQUESTED** [review]

**Review by guilhermebodin — APPROVED** [review]
